#!/bin/bash
#Starting by ensuring $LFS is linked to /mnt/lfs/
if [ "$LFS" = "/mnt/lfs/" ]
then
  echo "$LFS is set"
else
  export LFS="/mnt/lfs"
  echo "Export path done"
fi

mount -v -t ext4 /dev/sda3 $LFS;
echo "Drive mounted"

/sbin/swapon -v /dev/sda4;
echo "Swap mounted"

su - lfs;
