#!/bin/bash
#Starting by ensuring $LFS is linked to /mnt/lfs/
if [ "$LFS" = "/mnt/lfs/" ]
then
  echo "$LFS is set"
else
  export LFS="/mnt/lfs"
  echo "Export path done"
fi

mount -v -t ext4 /dev/sda3 $LFS;
echo "Drive mounted"

/sbin/swapon -v /dev/sda4;
echo "Swap mounted"

su - lfs;

cat > ~/.bash_profile << "EOF"
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
EOF

cat > ~/.bashrc << "EOF"
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/tools/bin:/bin:/usr/bin
export LFS LC_ALL LFS_TGT PATH
EOF

source ~/.bash_profile
